# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ca125429640e852506a400c13059f379f04dce615604e0b3bf5c179b8901290c7085ce32f5bb57e985266cd86d3402ed9e4bd914d8dc327fa25ef5c77b55630

test:
  secret_key_base: 8e1967846eea6944e6b95e9ddbe6c434c537ff1045433697c7943438ef37e74224a5d6bad0530fcd9edcba7187f31515349b1d9e2d230daa7c299967d36de5ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
